server:
  port: 8088
  servlet:
    context-path: /iam
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/iamservice"
    username: postgres
    password: "@Chuxuanloc26032003"
#    url: "jdbc:mysql://localhost:3306/iamservice"
#    username: root
#    password: 260303
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: chuxuanloc2003@gmail.com
    password: qhrv rtvp bzwp uhau
    # Sử dụng mật khẩu ứng dụng ở đây
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/CXL
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect  # Chỉ định Dialect cho PostgreSQL
    show-sql: true

security:
  authentication:
    jwt:
      key-store : keystore.jks
      key-store-password: cxlcxl
      key-alias: viz

#keycloak:
#  auth-server-url: http://localhost:8080/auth  # URL của Keycloak Server
#  realm: CXL  # Tên Realm trong Keycloak
#  resource: iam-service  # Client ID trong Keycloak
#  credentials:
#    secret: EEQnppsmXZDGIVhYOqJTGfiT47yY60qC  # Client Secret của client trong Keycloak
#  bearer-only: true  # Chỉ cho phép Bearer Token trong ứng dụng
#  security-constraints:
#    - authRoles:
#        - user  # Các role người dùng cần có để truy cập API
#      securityCollections:
#        - patterns:
#            - /api/*  # Bảo vệ các API có pattern là /api/*

jwt:
  valid-duration: 3600 #in second
  refreshable-duration: 360000 #insecond

idp:
  url: http://localhost:8080
  client-id: iam-service
  client-secret: EEQnppsmXZDGIVhYOqJTGfiT47yY60qC
#  client-secret: avNbp3yTahdCDjX0cWZi79TnQZ4KXASQ
  enable: false
  realms: CXL
feign:
  hystrix:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    version: openapi_3_0

# Lưu log vào file
  logging:
   file:
    name: =ogs/application.log   # Đường dẫn file log
    path: logs                  # Thư mục chứa log (nếu không chỉ định file cụ thể)
    max-size: 10MB
    max-history: 30





