server:
  port: 8088
  servlet:
    context-path: /iam
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/iamservice"
    username: postgres
    password: "@Chuxuanloc26032003"
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: chuxuanloc2003@gmail.com
    password: qhrv rtvp bzwp uhau
    # Sử dụng mật khẩu ứng dụng ở đây
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  jpa:
    hibernate:
#      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect  # Chỉ định Dialect cho PostgreSQL
    show-sql: true
security:
  authentication:
    jwt:
      key-store : keystore.jks
      key-store-password: cxlcxl
      key-alias: viz

jwt:
  signerKey: "wLaWr3+TMVjaUszxtX1Ib2sAjIPSW1IC5fmHmEhjFt9IX+LsYA1Ts8YMLUq5nOap"
  valid-duration: 3600 #in second
  refreshable-duration: 360000 #insecond



